package com.ings.gogo.homehuidata.db.moldeldata;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ings.gogo.homehuidata.db.surface.SurfaceModeldb0;
import com.ings.gogo.homehuidata.db.surface.SurfaceModeldb1;

import com.ings.gogo.homehuidata.db.moldeldata.SurfaceModeldb0Dao;
import com.ings.gogo.homehuidata.db.moldeldata.SurfaceModeldb1Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig surfaceModeldb0DaoConfig;
    private final DaoConfig surfaceModeldb1DaoConfig;

    private final SurfaceModeldb0Dao surfaceModeldb0Dao;
    private final SurfaceModeldb1Dao surfaceModeldb1Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        surfaceModeldb0DaoConfig = daoConfigMap.get(SurfaceModeldb0Dao.class).clone();
        surfaceModeldb0DaoConfig.initIdentityScope(type);

        surfaceModeldb1DaoConfig = daoConfigMap.get(SurfaceModeldb1Dao.class).clone();
        surfaceModeldb1DaoConfig.initIdentityScope(type);

        surfaceModeldb0Dao = new SurfaceModeldb0Dao(surfaceModeldb0DaoConfig, this);
        surfaceModeldb1Dao = new SurfaceModeldb1Dao(surfaceModeldb1DaoConfig, this);

        registerDao(SurfaceModeldb0.class, surfaceModeldb0Dao);
        registerDao(SurfaceModeldb1.class, surfaceModeldb1Dao);
    }
    
    public void clear() {
        surfaceModeldb0DaoConfig.clearIdentityScope();
        surfaceModeldb1DaoConfig.clearIdentityScope();
    }

    public SurfaceModeldb0Dao getSurfaceModeldb0Dao() {
        return surfaceModeldb0Dao;
    }

    public SurfaceModeldb1Dao getSurfaceModeldb1Dao() {
        return surfaceModeldb1Dao;
    }

}
